### ISSUE TITLE
xcode build failed

### ISSUE THREAD

**Issue by luctran** [luctran/Pairwise#1]
[weekdays.xcodeproj.zip](https://github.com/luctran/Pairwise/files/174422/weekdays.xcodeproj.zip)

When I try to build this, there are many syntax errors with the RCTSRWebSocket, RCTText, RCTLinking, RCTSetting, RCTActionSheet, and RCTNetwork. 

Tried updating my mac os, updating xcode, uninstalled watchmen to install HEAD watchman.

**Comment by StephenGrider** [comment]
What version of xcode did you update to?

**Comment by StephenGrider** [comment]
Also, can you zip up your entire project directory and share it?  I can't run the single xcodeproj file.

**Comment by luctran** [comment]
xcode 6.2

let me try. :)

**Comment by StephenGrider** [comment]
Ah, thats the issue then - you need to be on xcode 7.2  This is a requirement of react native, not my own :(

**Comment by luctran** [comment]
Ah, I'll try that. Head that it was a bad update.

**Comment by luctran** [comment]
Hey Stephen,

I've installed xcode 7.2.1, the latest on the app store, it allowed xcode
to build successfully, but when the emulator comes up, its a black screen
and its an emulator the the iphone 6s Plus. I tried to edit the
index.ios.js like you and reloaded the simulator to see if it works, but it
did not come up with the text as the code calls for.

**Comment by luctran** [comment]
I'm not sure what I did but I got it to work. :)
